### PR TITLE
Add built-in indexation

### PR DESCRIPTION
**Pull request by jdesboeufs**
And drop `lodash` dependency.

### CODE REVIEW

**Comment by jdesboeufs** [comment]
We could also process indexation in `prepublish`.

**Comment by MattiSG** [comment]
Why did you close? Superseded by #12?

**Comment by jdesboeufs** [comment]
Yes but finally we want this for the 1.x branch.

**Comment by MattiSG** [comment]
My thoughts exactly.
We should bump patch version in order to release that.

**Comment by jdesboeufs** [comment]
Already done with 6c54d9e

**Comment by MattiSG** [comment]
Yup but that changeset would appear after that commit & the `v1.0.2` tag. I prefer to release `v1.0.3` and be disciplined rather than have inconsistent VCS and publish histories.

**Pull request merged**
