### PR TITLE
add Section for other languages

### PR DESCRIPTION
**Pull request by Kleak**
add Section for other languages plus the link to the Dart library

### CODE REVIEW

**Comment by MattiSG** [comment]
Do you think you'd be able to follow the same versioning scheme and API signatures as ours? That way, users from one library could know that the API surface is the same as long as the versions match  :)

That can obviously wait for a few weeks if you want to make sure your implementation is not faulty, but would you agree on the end goal?

**Comment by Kleak** [comment]
The api is already the same as yours :)

**Comment by MattiSG** [comment]
Yes, but not the version number  ;)

**Comment by Kleak** [comment]
Ah yes not on the version number but i can push the same version no problem
:)
Could you if you make a change fill an issue on my repo ?

**Comment by MattiSG** [comment]
Will try to remember to push that info. No promises, but we’ll try  :)

**Comment by Kleak** [comment]
Great :)

**Comment by MattiSG** [comment]
@Kleak Would watching the repo do the job for you? This way we can just publish a release, and have GitHub notify you  :)

**Comment by Kleak** [comment]
Exact done ! :)

**Comment by Kleak** [comment]
Is there some other API that can be accessible from the web ?
Like that i can write Dart implementation to access the data :)

**Comment by MattiSG** [comment]
Great  :)

I think the API should match only for major + minor version numbers. No need to align patch versions, these can vary for each implementation. I'll document this.

**Comment by Kleak** [comment]
actually 1.0.x

**Comment by MattiSG** [comment]
> other API that can be accessible from the web ?

Check out the “OUVERT” APIs at https://api.gouv.fr  :)

**Comment by Kleak** [comment]
ok, you have a slack or something for speak about all that or everything is managed from github ?

**Comment by MattiSG** [comment]
We try to keep most discussions public, so that anyone is at the same page and can jump in  :)
(which also explains why we prefer English here: this API can be used by developers all over the world)

If you have more precise questions, don't hesitate to send a mail at contact@api.gouv.fr!

**Comment by Kleak** [comment]
ok should be cool to improve README of other API repos in order to invite developer to contribute.

**Comment by Kleak** [comment]
and maybe create a real API for code-postaux like that there is no need to update the dataset :)

**Comment by MattiSG** [comment]
Good idea! Have a look at #13

**Comment by Kleak** [comment]
yes i have seen :)

**Comment by MattiSG** [comment]
> a real API for code-postaux

Like the [GéoAPI](https://api.gouv.fr/api/geoapi) you mean?  :wink:

We do provide an API. But we won't handle the load for the whole world. The GéoAPI is a great way to build your service quickly, but it won't scale if you start handling lots of traffic. This module makes it easy for you to access the same database that powers the GéoAPI, on your own premises.

**Comment by Kleak** [comment]
Wohoo cool i haven't seen :)
ok i see there is no will to handle everything with api.gouv.fr for this but there is more information with the geoAPI than in the code-postaux package

**Comment by MattiSG** [comment]
I tried to make it clearer in #13, let me know if the intention is readable to you!  :)

**Pull request merged**
